### PR TITLE
Handle unsignable add-ons that need manual review

### LINKED ISSUE #407: jpm sign times out for listed + full review add-ons
To reproduce:

- submit an add-on to AMO and make it listed and request a full review
- get the initial add-on approved
- create a new version
- run `jpm sign` to auto-update the new version

This always ends in a time-out, with the following output:

````
$ jpm sign --api-key ... --api-secret ... --api-url-prefix http://olympia.dev/api/v3 --xpi ~/tmp/addons/scratch1/\@scratch1-0.0.4.xpi
JPM [info] Signing XPI: /Users/kumar/tmp/addons/scratch1/@scratch1-0.0.4.xpi
Validating add-on [......................................................................................................................................................................................]
JPM [error] FAIL
Error: Validation took too long to complete; last status: {"active":false,"url":"http://olympia.dev/api/v3/addons/%40scratch1/versions/0.0.4/uploads/256ab54aeb8f4163a264c57fb32848e4/","files":[{"hash":"sha256:6aab8ba9f66388e0e804d947c66f9a28ec8e0f595612a774ec6858959585640e","signed":false,"download_url":"http://olympia.dev/api/v3/file/132/scratch_1-0.0.4-fx+an.xpi?src=api"}],"passed_review":false,"pk":"256ab54aeb8f4163a264c57fb32848e4","processed":true,"reviewed":false,"valid":true,"validation_results":{"errors":0,"success":true,"warnings":0,"compatibi...
    at null._onTimeout (/Users/kumar/dev/jpm/lib/amo-client.js:151:14)
    at Timer.listOnTimeout (timers.js:110:15)
````

This is because the file will always require manual review since listed + full review gives it a side-loading certificate

### PR DESCRIPTION
**Pull request by kumar303**
Fixes #407

### CODE REVIEW

File: lib/amo-client.js [hunk 1]
```diff
@@ -116,17 +116,24 @@ Client.prototype.waitForSignedAddon = function(statusUrl, opt) {
...
 
         var failedValidation = !data.valid;
-        // The add-on passes validation and all files have been created.
-        var signedAndReady = (data.valid && data.reviewed && data.files &&
-                              data.files.length > 0);
+        // The add-on passed validation and all files have been created.
+        var signedAndReady = (data.valid && data.active && data.reviewed &&
+                              data.files && data.files.length > 0);
+        // The add-on is valid but requires a manual review before it can be signed.
+        var requiresManualReview = data.valid && !data.active && !data.reviewed;
```
Comment (mstriemer) [inline lib/amo-client.js]: The API should probably return `automated_signing` instead of making you do this.

**Comment by mstriemer** [comment]
API changes can happen later. r+
