### PR TITLE
Fix problems encountered with jshint

### LINKED ISSUE #328: Add ESLint (or something similar)
We should probably add ESLint to check for code quality and consistency.

Here's a starter .eslintignore and .eslintrc file and the current output:

### .eslintrc:
```yaml
extends: eslint:recommended

env:
  es6: true
  mocha: true
  node: true

rules:
  no-console: 0
  no-unused-vars: 0
```

### .eslintignore
```
test/addons/invalid-json/
```

### Output:
```
✗ eslint .

lib/init-input.js
  11:12  error  "prompt" is not defined  no-undef
  12:11  error  "prompt" is not defined  no-undef
  13:14  error  "prompt" is not defined  no-undef
  14:18  error  "prompt" is not defined  no-undef
  15:11  error  "prompt" is not defined  no-undef
  16:13  error  "prompt" is not defined  no-undef
  17:14  error  "prompt" is not defined  no-undef
  18:14  error  "prompt" is not defined  no-undef

lib/tmp.js
  12:14  error  Octal literals are not allowed in strict mode

lib/utils.js
  89:15  error  Empty block statement  no-empty

lib/xpi/utils.js
  15:7   error  tag is already defined     no-redeclare
  81:80  error  Unexpected trailing comma  comma-dangle

test/addon_runners/chrome/data/panel.js
  6:1  error  "self" is not defined  no-undef
  7:3  error  "self" is not defined  no-undef

test/addon_runners/chrome/main.js
  38:2  error  Mixed spaces and tabs  no-mixed-spaces-and-tabs
  41:2  error  Mixed spaces and tabs  no-mixed-spaces-and-tabs

test/addon_runners/main/main.js
  33:32  error  Unexpected identifier

test/addon_runners/unsafe-content-script/main.js
  40:13  error  "self" is not defined  no-undef
  43:13  error  "self" is not defined  no-undef

test/addons/extra-files/index.js
  41:56  error  Unexpected trailing comma  comma-dangle

test/addons/l10n-properties/test/test-main.js
  98:19  error  "document" is not defined  no-undef
  99:7   error  "self" is not defined      no-undef

test/fixtures/error-addon/index.js
  14:1  error  "sadf" is not defined  no-undef

test/fixtures/mock-sdk/lib/toolkit/loader.js
  334:38  error  Unexpected identifier

test/fixtures/param-dump/index.js
  43:56  error  Unexpected trailing comma  comma-dangle

test/unit/test.rdf.js
  154:11  error  xml is already defined     no-redeclare
  168:11  error  xml is already defined     no-redeclare
  177:11  error  xml is already defined     no-redeclare
  181:11  error  xml is already defined     no-redeclare
  256:34  error  Unexpected trailing comma  comma-dangle

✖ 30 problems (30 errors, 0 warnings)
```

### PR DESCRIPTION
**Pull request by nikolas**
And set the code up for automatic jshint validation.

Closes #328

### CODE REVIEW

File: lib/firefox.js [hunk 1]
```diff
@@ -124,24 +124,38 @@ function logFromAddon (manifest, line) {
 }
 
 function isErrorString (line) {
-  if (/^\*{25}/.test(line))
+  if (/^\*{25}/.test(line)) {
     return true;
-  if (/^\s*Message: [\D]*Error/.test(line))
+  }
```
Comment (kumar303) [inline lib/firefox.js]: :+1: thank you

File: lib/init-input.js [hunk 2]
```diff
@@ -1,3 +1,5 @@
+/* jshint ignore: start */
```
Comment (kumar303) [inline lib/init-input.js]: was this file too hard to fix up?

Comment (nikolas) [inline lib/init-input.js]: It seems this file isn't meant to be a valid javascript file. Notice how `prompt` is undefined, but this file still takes effect when you do `jpm init`. This is an input file for "promzard", see: https://github.com/npm/promzard#usage

File: test/addon_runners/author-email/main.js [hunk 3]
```diff
@@ -1,3 +1,4 @@
+/* jshint moz: true */
```
Comment (kumar303) [inline test/addon_runners/author-email/main.js]: cool, I didn't know about this option

File: test/addon_runners/chrome/data/panel.js [hunk 4]
```diff
@@ -1,3 +1,4 @@
+/* jshint ignore: start */
```
Comment (kumar303) [inline test/addon_runners/chrome/data/panel.js]: was this file too hard to fix?

File: test/fixtures/mock-sdk/lib/toolkit/loader.js [hunk 5]
```diff
@@ -759,14 +769,14 @@ const Loader = iced(function Loader(options) {
     load: { enumerable: false, value: options.load || load },
     // Main (entry point) module, it can be set only once, since loader
     // instance can have only one main module.
-    main: new function() {
+    main: function() {
```
Comment (kumar303) [inline test/fixtures/mock-sdk/lib/toolkit/loader.js]: I have no idea why this was using new. Some obscure trick maybe? Should we wrap it in an ignore?

File: test/addon_runners/chrome/data/panel.js (hunk 4 above)
Comment (nikolas) [inline test/addon_runners/chrome/data/panel.js]: I did that because this file was very short, and I didn't understand where `self` was defined, but I didn't want to change anything.

Note that in this branch, I'm excluding `test/addon_runners` from jshint checks because I couldn't get jshint's "esversion: 6" option to recognize the new `=>` syntax used throughout this code.

File: test/fixtures/mock-sdk/lib/toolkit/loader.js (hunk 5 above)
Comment (nikolas) [inline test/fixtures/mock-sdk/lib/toolkit/loader.js]: I'm not too worried about changing the semantics of this code, since it's just fixture code used by the tests. But yeah we could ignore this one if you think so.

File: lib/init-input.js (hunk 2 above)
Comment (kumar303) [inline lib/init-input.js]: Huh. Weird. Carry on then.

If you could put that explanation in a comment at the top then that would be helpful.

File: test/addon_runners/chrome/data/panel.js (hunk 4 above)
Comment (kumar303) [inline test/addon_runners/chrome/data/panel.js]: if you're ignoring this directing is the ignore comment still needed? Either way, sounds fine.

File: test/fixtures/mock-sdk/lib/toolkit/loader.js (hunk 5 above)
Comment (kumar303) [inline test/fixtures/mock-sdk/lib/toolkit/loader.js]: oh if it's a fixture and the tests pass then meh. It was probably just a typo, better to fix it.

**Comment by kumar303** [comment]
The npm docs doesn't say `pretest` will cause the tests to fail if there's an error but I assume it does? Did you see travis fail with a jshint error?

**Comment by nikolas** [comment]
Yeah, I put jshint in `pretest` so no tests are run if jshint doesn't pass and you just get the jshint error. I haven't seen the jshint error on travis since I made sure it was passing on my computer before pushing.

**Comment by kumar303** [comment]
> Yeah, I put jshint in pretest so no tests are run if jshint doesn't pass

Actually, I'd prefer to run the tests even if jshint fails. I like this approach because oftentimes jshint failures are just style nits. One sometimes has to wait a bit for tests on a PR to complete so I'd rather optimize for early test failures. Is there a way to run the test suite first then, if it passes, run the jshint checks?

**Comment by nikolas** [comment]
I took the jshint check out of pretest, it's now run with `npm run-script jshint`. I'm hoping it will behave like we want now.

**Comment by kumar303** [comment]
Yes, thanks. According to the Travis docs this will work as expected.

**Comment by kumar303** [comment]
@nikolas I went to add an indentation rule but I see that we need `jscs` for that. If you have any time to add that in, it be a big help. It looks like a lot of rules have been moved over to `jscs`.

**Comment by nikolas** [comment]
Yeah, that's true. I will look into adding jscs to jpm since I have some experience with that.
